# Generated by Django 4.2.4 on 2023-09-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp_blog', '0007_alter_comment_options_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='header',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
